name: Build APK

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore Android workloads
        run: dotnet workload restore
      - name: Restore dependencies
        run: dotnet restore involys/involys.csproj
      - name: Publish APK
        run: dotnet publish involys/involys.csproj -c Release -o out
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: out/*.apk
